### ISSUE TITLE
Oracle OAM

### ISSUE THREAD

**Issue by hoclun-rigsep** [megadix/create-react-app-servlet#1]
Hello and thank you for posting all this.

Do you have any advice on the simplest and most transparent way to combine your approach with a typical SSO setup using Oracle Access Manager?

Thanks in advance.

**Comment by megadix** [comment]
Hi,
hoclun-rigsep, sorry but I don't know how Oracle Access Manager works. I can imagine it requires some special routes to handle callbacks from SSO, in that case you have two possibilities:

### 1) Change folder structure

- move the existing code (`/src/App.js` etc.) under a new root, e.g. `src/main/react` and modify maven build file accordingly
- place Java webapp code under `/src/main/webapp`

### 2) Multi-module

You can create a multi-module project that assembles the WAR file combining a "react" module (exactly like the code in this repo) and a "webapp" module, with the special routes and configuration for OAM.

Again, I'm by no means an Oracle Access Manager expert, so these are just hypotheses!

Cheers,
Dimitri

[Closing the issue]

**Comment by hoclun-rigsep** [comment]
OK, thank you for taking the time to reply. 

>  I can imagine it requires some special routes to handle callbacks from SSO,

You might also imagine that it is not too difficult to find these things out, but that has not been my experience! The Oracle docs are byzantine at best. Nothing is dated, everything refers back to their proprietary GUI admin tools... it's turning into a bit of a nightmare.

Thank you for the advice.
