### ISSUE TITLE
After Successful deployment React components are not loading

### ISSUE THREAD

**Issue by kadiyan92** [megadix/create-react-app-servlet#2]
Hi

i have downloaded same application and tried after deployment , deployment was successful  but  blank page is coming.
should we need to include node_modules folder in war file.

Kindly help on the same

**Comment by megadix** [comment]
Hi,
`node_modules` should NOT be included in the war file, as Node modules are used only to build the client-side code. Maybe it's a problem with context mapping, check the original article on my website:
https://www.megadix.it/blog/create-react-app-servlet/

Unfortunately the code in this repository is quite old, I cannot test it easily. Sorry!
